language: php
sudo: true
php:
- 5.4
- hhvm
matrix:
  fast_finish: true
  allow_failures:
  - php: hhvm
env:
  global:
  - PATH="$PATH:$HOME/.composer/vendor/bin"
  - DRUPAL_TI_MODULE_NAME="scheduler"
  - DRUPAL_TI_SIMPLETEST_GROUP="Scheduler"
  - DRUPAL_TI_ENVIRONMENT="drupal-7"
  - DRUPAL_TI_DB="drupal_travis_db"
  - DRUPAL_TI_DB_URL="mysql://root:@127.0.0.1/drupal_travis_db"
  - DRUPAL_TI_WEBSERVER_URL="http://127.0.0.1"
  - DRUPAL_TI_WEBSERVER_PORT="8080"
  - DRUPAL_TI_SIMPLETEST_ARGS="--verbose --color --concurrency 4 --url $DRUPAL_TI_WEBSERVER_URL:$DRUPAL_TI_WEBSERVER_PORT"
  - DRUPAL_TI_BEHAT_DIR="./tests/behat"
  - DRUPAL_TI_BEHAT_ARGS=""
  - DRUPAL_TI_BEHAT_YML="behat.yml.dist"
  - DRUPAL_TI_BEHAT_SCREENSIZE_COLOR="1280x1024x16"
  - DRUPAL_TI_BEHAT_SELENIUM_VERSION="2.48.2"
  - DRUPAL_TI_BEHAT_DRIVER="phantomjs"
  - DRUPAL_TI_BEHAT_BROWSER="firefox"
  - DRUPAL_TI_PHPUNIT_ARGS=""
  - DRUPAL_TI_COVERAGE="satooshi/php-coveralls:0.6.*"
  - DRUPAL_TI_COVERAGE_FILE="build/logs/clover.xml"
  - secure: rQNcmmjsGd1pBhRwZ5nleo3/v4IhHSHcPPHIJfElLrRtSz2STowBwVbcNWVJyOD/8KIzItr+DhvDa2zZp5eBQK16xfDtShkEo9zaup4qdl8179FQPczEd3T7wRqdFqA4U1WwBcCoAqxHaG6BzPhVhI5tFaWqf3whjsTK+WH78XKEIMNvVaIccxgJRpbB/WZRlJ8QQlAw7NaZWjYacVS1kIwMITGh8734X3kCpgX+YdZiR8zmtGCDAU3RePNt7+KiVEHLrtSRfxpyt63BNGNwF1zLiCH+tzRB7ODDmff4c1LE4G1XgZm0JZih/zg8qxLTOUl/fNcLwb9rb8z/fZiNClU19CvxdW8wsTS1TVcODzDVeh3/yBGrnyXWZiDIL01bgXaj2bXPHVgMbT5RJ7CDTG2ZzvIJbp56ik4Kg9xkOW13uaEkehPYKqh8BGz+XTM5oI5ttsxpLukEj41ljss3o5AY0K52zIPxBQ8jtM868OourxMzLti8YCnLZ3+IuwEdd7ZSci7gHJayXqtuaVuaaXbpWnLVH5hDiPpskbJSBQvE2bLMJHNo175c5WUa45VlJ4wA42xL6KZ/WxHkWWnlfb1tX7jCoRTxOcbEMIQXsMzUTlIR1PTJA46msZOIrN/g3Dd3XH1RG+0NbXcF3WaYhYiQhBNLbIJyUZ+NhfGV+Yk=
  - secure: aZN/e666mRR9uDpOyJgDl7nSRFwnaltzMQYZ2y7WXVVxIEqsuyHF1ijqU3ShKNAFMQqHz28e/0QBhNbPD5Sj0fjO15GkZDUv22Ua7LpfEMtJHOj3e4MINB5oQd8sj1kYlUSIgksvO/no8V/0kvlqsmix1okF73xhh9Uc6v/94v3MTaRsfaufHjT6DYZMRdmPcsLPGqQnqaR0cgQ+lECYwSqbX5T7zZXP9g02SEmo8ClcMDn2HwT+biQtJI4OHWQHUb24+nt8JH/7vcij2oHOBpbsXIFpu4Qw7tsPYxqaylYi81Vz/wSKqiwMgxLyQRUTede92iQxZX/7kpzKB0SqPRfTa1ftM5AU+RMviiZP+aZr5zqzx5eRFSbryz+9+0ja/hLS9PvZZuioGWWjvLZ//mKpV/uW8H5TjOe1zA/KX3QEU33RC6ajfMfR7mfxQa4OcHOD82/gcdgpFqxNMuHDjWkgVWfgvFdkqPMuSRn7SEN9pY6aI+BbngBEi3zklC486L1FKdoNef+NFMBWfMkfNrzd43wyRIlZvS3a7no51nYetE+rK0L4uA1VSutSzrRjusDCfPoIndM28gNk7+VERsWbH/VyymjEA2hC1Bfyn6+UGBKkd9Z0Yg3yAhbT81ZuJyzFxerB4WJNsHgACUPiPufeZ8BisLc119gaUMXVZHU=
  - secure: AUBulwJksfEDbS/yCaiSbM9H8i/U6BwtbKYyVZiW2TfUxeZekEgWdpi8BD6x2A6Wj6Poo4xE/S0+zJK5yNzuLnKxKebREMTEoU3bLUt9/Ckg71gfTBWQfVeqxgcf30vwSBTSRixoZvmrExKa10Y64Sx7iZKNH0v2OXY+OFJ1UGKZabE+kOX+5QJNiIGe/PROR6WW8ug7FKxg+VcFQPLn03MKEiLseWevmLIX2YecSucJUIFphAyHPr+Pg20vu3FjzhueOpWDYfpkdd3370lMgydcev2Yfgt68amTPhlGjxeMza5oyZTsSWe0hDpR0q3I9dXooz6MGMctjfFFEPct8axc9nk4lpiOx8JFY+6vWfasRP1CMn/TU5bsfSLJehzFdrtLAcFjJaxh1+JqCuKszEyZumLryWRpaodsHzCMURZkpYUegCRLAXPS0ArLlVSX8UEDXq/Me0qn4DjHRjqJVT7pUjUHEo7Mqb9diHzPf5kdz1b/LXKM2IhZNvKNLODS2kohWmb3NZIycvlwqN6OD61ilNPq2xJ0RHru/j8YhIc4cmY2BGjgxOfILUhmUFO/meWsoDbU4Hvr4RQSbJxfumxTcM1+7IoMnjUQjmQCX51pM5EdSI9Qsalxyw/Tb1DJJ1/EwrQa/Ycgib3TLZJxbgAhXgr/BFYQW/fOCUAuf6M=
  - secure: h5Z5EF7nuj/6YmMm7mGCgZWLjURdjhxjdLU3nQcbkqRavhQKyFlqL0nrsETVYs0BZ8PHsaJpQTMu6v8RuGecqck7y8R5Y1iF8GaWeyf/tevDU1dOPf0sIgzkeH8jSfilWfJeWlXpfF8vyhsSbB97Pir5A3lucA7ByyGtnr5JD1odf0SYGyV5lZwGsF6pAUSNk/4Rhm30nMwzzdTO+k89EGmPboFHO2funxsf/VnaWHKh/zEo7R3WuTPcFWqvDoXutmZAP5z1MTmKPXAub5uyRuj1D057wZQ2CjPFCr3V2EN8T8RkFxogGnZq7zakks+XekK2zw/Lc4jg6hBmhAjQhTLPcxXDo3MQWClB5WNFjn6Ruiluvd2QfBF+A5rESK9fTlDxSs1wr+9kQfc+YH25ekvW32gUC/rs7IrDzSl7bOTXiyrdDrpycdv2pl/DPgPNjsDG67wjhcx6BNqOrcD5ZBW3Tmd8eLqLP/K45QV4Gf4vXSdTvrvoyH7qB6WuvQ/o40Oor8DrfGrgSmiSIaiHck6JUPp4XdzzYWhJgnUJ9naIxx8WB+kpMVHpF00kKgBuXm3wXEFwlT+vZ/WwkxVtRYEMEPHBYfDC09cVKOQS4bzfS/V/pn2yP0zhHJgd1iKb37nnNSsSJBIP3u5w/NaptAawQcm9/qzYWmZXCgyRnjc=
  matrix:
  - DRUPAL_TI_RUNNERS="simpletest"
mysql:
  database: drupal_travis_db
  username: root
  encoding: utf8
before_install:
- wget --help
- cp -R /home/travis/build/legovaer/scheduler /home/travis/scheduler
- sudo apt-get install php5-xdebug
- sudo git clone https://github.com/simpletest/simpletest.git /usr/local/simpletest
- composer self-update
- cd ./tests
- git clone --branch dev-add-coverage-support https://github.com/legovaer/drupal_ti
- cd drupal_ti/
- composer install
- mkdir -p "$HOME/.composer/vendor/bin"
- ln -sf $(pwd)/drupal_ti/drupal-ti "$HOME/.composer/vendor/bin"
- cd $TRAVIS_BUILD_DIR/tests

#- wget  http://ftp.gnu.org/gnu/wget/wget-1.16.tar.gz
#- tar -xzf wget-1.16.tar.gz
#- cd wget-1.16
#- ./configure
#- ./configure --with-ssl=openssl
#- sudo make && sudo make install
#- sudo apt-get install --only-upgrade wget
#- wget http://cz.archive.ubuntu.com/ubuntu/pool/main/w/wget/wget_1.13.4-2ubuntu1.2_i386.deb
#- sudo dpkg -i
#- wget -V
- drupal-ti before_install
- php $TRAVIS_BUILD_DIR/drupal_ti/before/before_install.php

install:
- drupal-ti install
before_script:
- drupal-ti --include "$TRAVIS_BUILD_DIR/drupal_ti/before/before_script.sh"
- drupal-ti before_script
script:
- drupal-ti script
after_script:
- drupal-ti --include "$TRAVIS_BUILD_DIR/drupal_ti/after/after_script.sh"
- drupal-ti after_script
notifications:
  email: false
