language: php
sudo: true
php:
- 5.4
- hhvm
matrix:
  fast_finish: true
  allow_failures:
  - php: hhvm
env:
  global:
  - PATH="$PATH:$HOME/.composer/vendor/bin"
  - DRUPAL_TI_MODULE_NAME="scheduler"
  - DRUPAL_TI_SIMPLETEST_GROUP="Scheduler"
  - DRUPAL_TI_ENVIRONMENT="drupal-7"
  - DRUPAL_TI_DB="drupal_travis_db"
  - DRUPAL_TI_DB_URL="mysql://root:@127.0.0.1/drupal_travis_db"
  - DRUPAL_TI_WEBSERVER_URL="http://127.0.0.1"
  - DRUPAL_TI_WEBSERVER_PORT="8080"
  - DRUPAL_TI_SIMPLETEST_ARGS="--verbose --color --concurrency 4 --url $DRUPAL_TI_WEBSERVER_URL:$DRUPAL_TI_WEBSERVER_PORT"
  - DRUPAL_TI_BEHAT_DIR="./tests/behat"
  - DRUPAL_TI_BEHAT_ARGS=""
  - DRUPAL_TI_BEHAT_YML="behat.yml.dist"
  - DRUPAL_TI_BEHAT_SCREENSIZE_COLOR="1280x1024x16"
  - DRUPAL_TI_BEHAT_SELENIUM_VERSION="2.48.2"
  - DRUPAL_TI_BEHAT_DRIVER="phantomjs"
  - DRUPAL_TI_BEHAT_BROWSER="firefox"
  - DRUPAL_TI_PHPUNIT_ARGS=""
  - DRUPAL_TI_COVERAGE="satooshi/php-coveralls:0.6.*"
  - DRUPAL_TI_COVERAGE_FILE="build/logs/clover.xml"
  - secure: jvsD+gsl5uftq7DGw0uCk8YKKSW0F6yweLU8cTz81MMVnpnO8q/+YBE1tBzE8j5gfqV/R67SGGn1CDckbylsah8RdTbzdDqNc+Dnr1LTUIx94OuiqJOzEj85n8Ui0y9cIn1oxML9h1PKZRvDF6Pls49UcMIpT5qkTyCcp8T2xsLyoV2YcjVVddzpjumZAB2v4boH3FKKRauodHdqYOmprYNXZ/yiHuTaS/NpJadowrkP5COu303Z0zWgCdaWzzP+S+BZJcnRBc9A82B3sp7p9qmSFdz1+Ue3We4tLjH20dtiNW3B73EK5lDky1IzltBQmN4srZ77yAvGMYqesg+x36dnmfuGmleCrVLMuWITtFd6Q/QuZ3fhiEKsGGioJRki3kKM9XK5UR7Lo1kQ8w2yILgPsFlXxz9O0vut4QzUcjFbqUie/2ClT+NbCo3vRmEQMrwqVkJDKToF6YpfKnx9UgVbUvHBrx6XlRfcsQnM2ve2A2qDViFMc48/jy0Dk3NYmgiz5qhbTmRrop/YXZPLpOlq2soA9EgWfUey5kez5VpPaqVczkh2IMeRm/zyBkygzShZ+Z9hsqUnGa9rwyMrY4KDGfzjcwpaK5H75RRCF6tp2dBUCCgIt78BoYyuJ9lAu8pqhr1jCZleU0eR1jFJstrOo5AsgxcZ7Y7wYTk2MzI=
  matrix:
  - DRUPAL_TI_RUNNERS="simpletest"
mysql:
  database: drupal_travis_db
  username: root
  encoding: utf8
before_install:
- sudo apt-get install php5-xdebug
- sudo git clone https://github.com/simpletest/simpletest.git /usr/local/simpletest
- composer self-update
- cd ./tests
- composer global require "lionsad/drupal_ti:dev-master"
- drupal-ti before_install
install:
- drupal-ti install
before_script:
- git config --global user.email "levi.govaerts@capgemini.com"
- git config --global user.name "Travis-CI"
- git config --global push.default simple
- cd "$DRUPAL_TI_DRUPAL_DIR"
- wget https://www.drupal.org/files/issues/2189345-39.patch
- git apply -v 2189345-39.patch
- drupal-ti before_script
script:
- drupal-ti --include "$TRAVIS_BUILD_DIR/drupal_ti/before/before_script.sh"
- drupal-ti script
after_script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://jvsD+gsl5uftq7DGw0uCk8YKKSW0F6yweLU8cTz81MMVnpnO8q/+YBE1tBzE8j5gfqV/R67SGGn1CDckbylsah8RdTbzdDqNc+Dnr1LTUIx94OuiqJOzEj85n8Ui0y9cIn1oxML9h1PKZRvDF6Pls49UcMIpT5qkTyCcp8T2xsLyoV2YcjVVddzpjumZAB2v4boH3FKKRauodHdqYOmprYNXZ/yiHuTaS/NpJadowrkP5COu303Z0zWgCdaWzzP+S+BZJcnRBc9A82B3sp7p9qmSFdz1+Ue3We4tLjH20dtiNW3B73EK5lDky1IzltBQmN4srZ77yAvGMYqesg+x36dnmfuGmleCrVLMuWITtFd6Q/QuZ3fhiEKsGGioJRki3kKM9XK5UR7Lo1kQ8w2yILgPsFlXxz9O0vut4QzUcjFbqUie/2ClT+NbCo3vRmEQMrwqVkJDKToF6YpfKnx9UgVbUvHBrx6XlRfcsQnM2ve2A2qDViFMc48/jy0Dk3NYmgiz5qhbTmRrop/YXZPLpOlq2soA9EgWfUey5kez5VpPaqVczkh2IMeRm/zyBkygzShZ+Z9hsqUnGa9rwyMrY4KDGfzjcwpaK5H75RRCF6tp2dBUCCgIt78BoYyuJ9lAu8pqhr1jCZleU0eR1jFJstrOo5AsgxcZ7Y7wYTk2MzI=:@github.com" > .git/credentials
- cd "/home/travis/build/legovaer/drupal-7/drupal"
- git clone --branch 7.x-1.x-reports https://github.com/legovaer/scheduler.git coverage-report
- rm -rf coverage-report/*
- php /usr/local/simpletest/extensions/coverage/bin/php-coverage-close.php
- php /usr/local/simpletest/extensions/coverage/bin/php-coverage-report.php
- cd coverage-report/
- git add *
- git commit -m "Added report for $TRAVIS_BUILD_NUMBER"
- git push
- git tag $TRAVIS_BUILD_NUMBER
- git push --tags
- drupal-ti after_script
notifications:
  email: false
